const RAW: Record<string, [string, string]> = {
  AAPL: ["Apple Inc.", "Technology"],
  MSFT: ["Microsoft Corp.", "Technology"],
  NVDA: ["NVIDIA Corp.", "Technology"],
  AVGO: ["Broadcom Inc.", "Technology"],
  ORCL: ["Oracle Corp.", "Technology"],
  CRM: ["Salesforce Inc.", "Technology"],
  ADBE: ["Adobe Inc.", "Technology"],
  CSCO: ["Cisco Systems", "Technology"],
  ACN: ["Accenture plc", "Technology"],
  AMD: ["Advanced Micro Devices", "Technology"],
  INTC: ["Intel Corp.", "Technology"],
  QCOM: ["Qualcomm Inc.", "Technology"],
  TXN: ["Texas Instruments", "Technology"],
  IBM: ["IBM", "Technology"],
  NOW: ["ServiceNow Inc.", "Technology"],
  INTU: ["Intuit Inc.", "Technology"],
  AMAT: ["Applied Materials", "Technology"],
  MU: ["Micron Technology", "Technology"],
  ADI: ["Analog Devices", "Technology"],
  LRCX: ["Lam Research", "Technology"],
  KLAC: ["KLA Corp.", "Technology"],
  PANW: ["Palo Alto Networks", "Technology"],
  SNPS: ["Synopsys Inc.", "Technology"],
  CDNS: ["Cadence Design Systems", "Technology"],
  MCHP: ["Microchip Technology", "Technology"],
  NXPI: ["NXP Semiconductors", "Technology"],
  DELL: ["Dell Technologies", "Technology"],
  HPQ: ["HP Inc.", "Technology"],
  HPE: ["Hewlett Packard Enterprise", "Technology"],
  CRWD: ["CrowdStrike Holdings", "Technology"],
  PLTR: ["Palantir Technologies", "Technology"],
  SNOW: ["Snowflake Inc.", "Technology"],
  SMCI: ["Super Micro Computer", "Technology"],
  ANET: ["Arista Networks", "Technology"],
  WDAY: ["Workday Inc.", "Technology"],

  GOOGL: ["Alphabet Inc.", "Communication Services"],
  GOOG: ["Alphabet Inc.", "Communication Services"],
  META: ["Meta Platforms", "Communication Services"],
  NFLX: ["Netflix Inc.", "Communication Services"],
  DIS: ["Walt Disney Co.", "Communication Services"],
  CMCSA: ["Comcast Corp.", "Communication Services"],
  T: ["AT&T Inc.", "Communication Services"],
  VZ: ["Verizon Communications", "Communication Services"],
  TMUS: ["T-Mobile US", "Communication Services"],
  CHTR: ["Charter Communications", "Communication Services"],
  EA: ["Electronic Arts", "Communication Services"],
  TTWO: ["Take-Two Interactive", "Communication Services"],
  WBD: ["Warner Bros. Discovery", "Communication Services"],
  OMC: ["Omnicom Group", "Communication Services"],
  LYV: ["Live Nation Entertainment", "Communication Services"],
  SPOT: ["Spotify Technology", "Communication Services"],

  AMZN: ["Amazon.com Inc.", "Consumer Discretionary"],
  TSLA: ["Tesla Inc.", "Consumer Discretionary"],
  HD: ["Home Depot", "Consumer Discretionary"],
  LOW: ["Lowe's Companies", "Consumer Discretionary"],
  MCD: ["McDonald's Corp.", "Consumer Discretionary"],
  NKE: ["Nike Inc.", "Consumer Discretionary"],
  SBUX: ["Starbucks Corp.", "Consumer Discretionary"],
  BKNG: ["Booking Holdings", "Consumer Discretionary"],
  TJX: ["TJX Companies", "Consumer Discretionary"],
  CMG: ["Chipotle Mexican Grill", "Consumer Discretionary"],
  ABNB: ["Airbnb Inc.", "Consumer Discretionary"],
  MAR: ["Marriott International", "Consumer Discretionary"],
  GM: ["General Motors", "Consumer Discretionary"],
  F: ["Ford Motor Co.", "Consumer Discretionary"],
  LULU: ["Lululemon Athletica", "Consumer Discretionary"],
  ROST: ["Ross Stores", "Consumer Discretionary"],
  ORLY: ["O'Reilly Automotive", "Consumer Discretionary"],
  AZO: ["AutoZone Inc.", "Consumer Discretionary"],
  YUM: ["Yum! Brands", "Consumer Discretionary"],
  DHI: ["D.R. Horton", "Consumer Discretionary"],
  LEN: ["Lennar Corp.", "Consumer Discretionary"],
  EBAY: ["eBay Inc.", "Consumer Discretionary"],
  TGT: ["Target Corp.", "Consumer Discretionary"],

  WMT: ["Walmart Inc.", "Consumer Staples"],
  COST: ["Costco Wholesale", "Consumer Staples"],
  PG: ["Procter & Gamble", "Consumer Staples"],
  KO: ["Coca-Cola Co.", "Consumer Staples"],
  PEP: ["PepsiCo Inc.", "Consumer Staples"],
  PM: ["Philip Morris International", "Consumer Staples"],
  MO: ["Altria Group", "Consumer Staples"],
  MDLZ: ["Mondelez International", "Consumer Staples"],
  CL: ["Colgate-Palmolive", "Consumer Staples"],
  KMB: ["Kimberly-Clark", "Consumer Staples"],
  GIS: ["General Mills", "Consumer Staples"],
  KHC: ["Kraft Heinz", "Consumer Staples"],
  STZ: ["Constellation Brands", "Consumer Staples"],
  KDP: ["Keurig Dr Pepper", "Consumer Staples"],
  MNST: ["Monster Beverage", "Consumer Staples"],
  HSY: ["Hershey Co.", "Consumer Staples"],
  ADM: ["Archer-Daniels-Midland", "Consumer Staples"],
  CLX: ["Clorox Co.", "Consumer Staples"],
  EL: ["Estée Lauder", "Consumer Staples"],


  "BRK.B": ["Berkshire Hathaway", "Financials"],
  JPM: ["JPMorgan Chase", "Financials"],
  BAC: ["Bank of America", "Financials"],
  WFC: ["Wells Fargo", "Financials"],
  GS: ["Goldman Sachs", "Financials"],
  MS: ["Morgan Stanley", "Financials"],
  C: ["Citigroup Inc.", "Financials"],
  V: ["Visa Inc.", "Financials"],
  MA: ["Mastercard Inc.", "Financials"],
  AXP: ["American Express", "Financials"],
  BLK: ["BlackRock Inc.", "Financials"],
  SCHW: ["Charles Schwab", "Financials"],
  SPGI: ["S&P Global", "Financials"],
  CB: ["Chubb Ltd.", "Financials"],
  PGR: ["Progressive Corp.", "Financials"],
  MMC: ["Marsh & McLennan", "Financials"],
  USB: ["U.S. Bancorp", "Financials"],
  PNC: ["PNC Financial Services", "Financials"],
  TFC: ["Truist Financial", "Financials"],
  COF: ["Capital One Financial", "Financials"],
  MET: ["MetLife Inc.", "Financials"],
  AIG: ["American International Group", "Financials"],
  PRU: ["Prudential Financial", "Financials"],
  TRV: ["Travelers Companies", "Financials"],
  ICE: ["Intercontinental Exchange", "Financials"],
  CME: ["CME Group", "Financials"],
  MCO: ["Moody's Corp.", "Financials"],
  PYPL: ["PayPal Holdings", "Financials"],

  UNH: ["UnitedHealth Group", "Health Care"],
  JNJ: ["Johnson & Johnson", "Health Care"],
  LLY: ["Eli Lilly & Co.", "Health Care"],
  MRK: ["Merck & Co.", "Health Care"],
  ABBV: ["AbbVie Inc.", "Health Care"],
  PFE: ["Pfizer Inc.", "Health Care"],
  TMO: ["Thermo Fisher Scientific", "Health Care"],
  ABT: ["Abbott Laboratories", "Health Care"],
  DHR: ["Danaher Corp.", "Health Care"],
  BMY: ["Bristol-Myers Squibb", "Health Care"],
  AMGN: ["Amgen Inc.", "Health Care"],
  MDT: ["Medtronic plc", "Health Care"],
  GILD: ["Gilead Sciences", "Health Care"],
  CVS: ["CVS Health", "Health Care"],
  ELV: ["Elevance Health", "Health Care"],
  CI: ["Cigna Group", "Health Care"],
  ISRG: ["Intuitive Surgical", "Health Care"],
  VRTX: ["Vertex Pharmaceuticals", "Health Care"],
  REGN: ["Regeneron Pharmaceuticals", "Health Care"],
  ZTS: ["Zoetis Inc.", "Health Care"],
  BSX: ["Boston Scientific", "Health Care"],
  SYK: ["Stryker Corp.", "Health Care"],
  HCA: ["HCA Healthcare", "Health Care"],
  BDX: ["Becton Dickinson", "Health Care"],
  MRNA: ["Moderna Inc.", "Health Care"],
  BIIB: ["Biogen Inc.", "Health Care"],
  HUM: ["Humana Inc.", "Health Care"],

  BA: ["Boeing Co.", "Industrials"],
  CAT: ["Caterpillar Inc.", "Industrials"],
  DE: ["Deere & Co.", "Industrials"],
  GE: ["GE Aerospace", "Industrials"],
  HON: ["Honeywell International", "Industrials"],
  UPS: ["United Parcel Service", "Industrials"],
  RTX: ["RTX Corp.", "Industrials"],
  LMT: ["Lockheed Martin", "Industrials"],
  NOC: ["Northrop Grumman", "Industrials"],
  GD: ["General Dynamics", "Industrials"],
  UNP: ["Union Pacific", "Industrials"],
  MMM: ["3M Co.", "Industrials"],
  FDX: ["FedEx Corp.", "Industrials"],
  EMR: ["Emerson Electric", "Industrials"],
  ETN: ["Eaton Corp.", "Industrials"],
  ITW: ["Illinois Tool Works", "Industrials"],
  CSX: ["CSX Corp.", "Industrials"],
  NSC: ["Norfolk Southern", "Industrials"],
  WM: ["Waste Management", "Industrials"],
  PH: ["Parker Hannifin", "Industrials"],
  LHX: ["L3Harris Technologies", "Industrials"],
  TDG: ["TransDigm Group", "Industrials"],
  PCAR: ["PACCAR Inc.", "Industrials"],
  CMI: ["Cummins Inc.", "Industrials"],


  XOM: ["Exxon Mobil", "Energy"],
  CVX: ["Chevron Corp.", "Energy"],
  COP: ["ConocoPhillips", "Energy"],
  SLB: ["Schlumberger Ltd.", "Energy"],
  EOG: ["EOG Resources", "Energy"],
  MPC: ["Marathon Petroleum", "Energy"],
  PSX: ["Phillips 66", "Energy"],
  VLO: ["Valero Energy", "Energy"],
  OXY: ["Occidental Petroleum", "Energy"],
  WMB: ["Williams Companies", "Energy"],
  KMI: ["Kinder Morgan", "Energy"],
  HAL: ["Halliburton Co.", "Energy"],
  DVN: ["Devon Energy", "Energy"],
  HES: ["Hess Corp.", "Energy"],
  FANG: ["Diamondback Energy", "Energy"],
  OKE: ["ONEOK Inc.", "Energy"],
  LNG: ["Cheniere Energy", "Energy"],

  NEE: ["NextEra Energy", "Utilities"],
  DUK: ["Duke Energy", "Utilities"],
  SO: ["Southern Co.", "Utilities"],
  D: ["Dominion Energy", "Utilities"],
  AEP: ["American Electric Power", "Utilities"],
  EXC: ["Exelon Corp.", "Utilities"],
  SRE: ["Sempra", "Utilities"],
  XEL: ["Xcel Energy", "Utilities"],
  ED: ["Consolidated Edison", "Utilities"],
  PEG: ["Public Service Enterprise", "Utilities"],
  PCG: ["PG&E Corp.", "Utilities"],

  AMT: ["American Tower", "Real Estate"],
  PLD: ["Prologis Inc.", "Real Estate"],
  CCI: ["Crown Castle", "Real Estate"],
  EQIX: ["Equinix Inc.", "Real Estate"],
  PSA: ["Public Storage", "Real Estate"],
  O: ["Realty Income", "Real Estate"],
  SPG: ["Simon Property Group", "Real Estate"],
  WELL: ["Welltower Inc.", "Real Estate"],
  DLR: ["Digital Realty Trust", "Real Estate"],

  LIN: ["Linde plc", "Materials"],
  APD: ["Air Products & Chemicals", "Materials"],
  SHW: ["Sherwin-Williams", "Materials"],
  ECL: ["Ecolab Inc.", "Materials"],
  FCX: ["Freeport-McMoRan", "Materials"],
  NEM: ["Newmont Corp.", "Materials"],
  DOW: ["Dow Inc.", "Materials"],
  NUE: ["Nucor Corp.", "Materials"],
  CTVA: ["Corteva Inc.", "Materials"],
}

export type StaticProfile = { name: string; sector: string }

export function staticProfile(ticker: string): StaticProfile | null {
  const hit = RAW[ticker.trim().toUpperCase()]
  return hit ? { name: hit[0], sector: hit[1] } : null
}
