"""Static ticker -> GICS sector map (generated from the backend
services/sector_map.py large-cap table). Pure DATA, no imports — a
leak-free fallback for the market/committee/PAC sector lookup when the
FMP profiles snapshot is absent or quota-limited. Company->sector is static
metadata (not time-varying), so applying it across folds is not leakage.
"""

STATIC_SECTOR: dict[str, str] = {
    'AAPL': 'Technology',
    'ABBV': 'Health Care',
    'ABNB': 'Consumer Discretionary',
    'ABT': 'Health Care',
    'ACN': 'Technology',
    'ADBE': 'Technology',
    'ADI': 'Technology',
    'ADM': 'Consumer Staples',
    'AEP': 'Utilities',
    'AIG': 'Financials',
    'AMAT': 'Technology',
    'AMD': 'Technology',
    'AMGN': 'Health Care',
    'AMT': 'Real Estate',
    'AMZN': 'Consumer Discretionary',
    'ANET': 'Technology',
    'APD': 'Materials',
    'AVGO': 'Technology',
    'AXP': 'Financials',
    'AZO': 'Consumer Discretionary',
    'BA': 'Industrials',
    'BAC': 'Financials',
    'BDX': 'Health Care',
    'BIIB': 'Health Care',
    'BKNG': 'Consumer Discretionary',
    'BLK': 'Financials',
    'BMY': 'Health Care',
    'BRK.B': 'Financials',
    'BSX': 'Health Care',
    'C': 'Financials',
    'CAT': 'Industrials',
    'CB': 'Financials',
    'CCI': 'Real Estate',
    'CDNS': 'Technology',
    'CHTR': 'Communication Services',
    'CI': 'Health Care',
    'CL': 'Consumer Staples',
    'CLX': 'Consumer Staples',
    'CMCSA': 'Communication Services',
    'CME': 'Financials',
    'CMG': 'Consumer Discretionary',
    'CMI': 'Industrials',
    'COF': 'Financials',
    'COP': 'Energy',
    'COST': 'Consumer Staples',
    'CRM': 'Technology',
    'CRWD': 'Technology',
    'CSCO': 'Technology',
    'CSX': 'Industrials',
    'CTVA': 'Materials',
    'CVS': 'Health Care',
    'CVX': 'Energy',
    'D': 'Utilities',
    'DE': 'Industrials',
    'DELL': 'Technology',
    'DHI': 'Consumer Discretionary',
    'DHR': 'Health Care',
    'DIS': 'Communication Services',
    'DLR': 'Real Estate',
    'DOW': 'Materials',
    'DUK': 'Utilities',
    'DVN': 'Energy',
    'EA': 'Communication Services',
    'EBAY': 'Consumer Discretionary',
    'ECL': 'Materials',
    'ED': 'Utilities',
    'EL': 'Consumer Staples',
    'ELV': 'Health Care',
    'EMR': 'Industrials',
    'EOG': 'Energy',
    'EQIX': 'Real Estate',
    'ETN': 'Industrials',
    'EXC': 'Utilities',
    'F': 'Consumer Discretionary',
    'FANG': 'Energy',
    'FCX': 'Materials',
    'FDX': 'Industrials',
    'GD': 'Industrials',
    'GE': 'Industrials',
    'GILD': 'Health Care',
    'GIS': 'Consumer Staples',
    'GM': 'Consumer Discretionary',
    'GOOG': 'Communication Services',
    'GOOGL': 'Communication Services',
    'GS': 'Financials',
    'HAL': 'Energy',
    'HCA': 'Health Care',
    'HD': 'Consumer Discretionary',
    'HES': 'Energy',
    'HON': 'Industrials',
    'HPE': 'Technology',
    'HPQ': 'Technology',
    'HSY': 'Consumer Staples',
    'HUM': 'Health Care',
    'IBM': 'Technology',
    'ICE': 'Financials',
    'INTC': 'Technology',
    'INTU': 'Technology',
    'ISRG': 'Health Care',
    'ITW': 'Industrials',
    'JNJ': 'Health Care',
    'JPM': 'Financials',
    'KDP': 'Consumer Staples',
    'KHC': 'Consumer Staples',
    'KLAC': 'Technology',
    'KMB': 'Consumer Staples',
    'KMI': 'Energy',
    'KO': 'Consumer Staples',
    'LEN': 'Consumer Discretionary',
    'LHX': 'Industrials',
    'LIN': 'Materials',
    'LLY': 'Health Care',
    'LMT': 'Industrials',
    'LNG': 'Energy',
    'LOW': 'Consumer Discretionary',
    'LRCX': 'Technology',
    'LULU': 'Consumer Discretionary',
    'LYV': 'Communication Services',
    'MA': 'Financials',
    'MAR': 'Consumer Discretionary',
    'MCD': 'Consumer Discretionary',
    'MCHP': 'Technology',
    'MCO': 'Financials',
    'MDLZ': 'Consumer Staples',
    'MDT': 'Health Care',
    'MET': 'Financials',
    'META': 'Communication Services',
    'MMC': 'Financials',
    'MMM': 'Industrials',
    'MNST': 'Consumer Staples',
    'MO': 'Consumer Staples',
    'MPC': 'Energy',
    'MRK': 'Health Care',
    'MRNA': 'Health Care',
    'MS': 'Financials',
    'MSFT': 'Technology',
    'MU': 'Technology',
    'NEE': 'Utilities',
    'NEM': 'Materials',
    'NFLX': 'Communication Services',
    'NKE': 'Consumer Discretionary',
    'NOC': 'Industrials',
    'NOW': 'Technology',
    'NSC': 'Industrials',
    'NUE': 'Materials',
    'NVDA': 'Technology',
    'NXPI': 'Technology',
    'O': 'Real Estate',
    'OKE': 'Energy',
    'OMC': 'Communication Services',
    'ORCL': 'Technology',
    'ORLY': 'Consumer Discretionary',
    'OXY': 'Energy',
    'PANW': 'Technology',
    'PCAR': 'Industrials',
    'PCG': 'Utilities',
    'PEG': 'Utilities',
    'PEP': 'Consumer Staples',
    'PFE': 'Health Care',
    'PG': 'Consumer Staples',
    'PGR': 'Financials',
    'PH': 'Industrials',
    'PLD': 'Real Estate',
    'PLTR': 'Technology',
    'PM': 'Consumer Staples',
    'PNC': 'Financials',
    'PRU': 'Financials',
    'PSA': 'Real Estate',
    'PSX': 'Energy',
    'PYPL': 'Financials',
    'QCOM': 'Technology',
    'REGN': 'Health Care',
    'ROST': 'Consumer Discretionary',
    'RTX': 'Industrials',
    'SBUX': 'Consumer Discretionary',
    'SCHW': 'Financials',
    'SHW': 'Materials',
    'SLB': 'Energy',
    'SMCI': 'Technology',
    'SNOW': 'Technology',
    'SNPS': 'Technology',
    'SO': 'Utilities',
    'SPG': 'Real Estate',
    'SPGI': 'Financials',
    'SPOT': 'Communication Services',
    'SRE': 'Utilities',
    'STZ': 'Consumer Staples',
    'SYK': 'Health Care',
    'T': 'Communication Services',
    'TDG': 'Industrials',
    'TFC': 'Financials',
    'TGT': 'Consumer Discretionary',
    'TJX': 'Consumer Discretionary',
    'TMO': 'Health Care',
    'TMUS': 'Communication Services',
    'TRV': 'Financials',
    'TSLA': 'Consumer Discretionary',
    'TTWO': 'Communication Services',
    'TXN': 'Technology',
    'UNH': 'Health Care',
    'UNP': 'Industrials',
    'UPS': 'Industrials',
    'USB': 'Financials',
    'V': 'Financials',
    'VLO': 'Energy',
    'VRTX': 'Health Care',
    'VZ': 'Communication Services',
    'WBD': 'Communication Services',
    'WDAY': 'Technology',
    'WELL': 'Real Estate',
    'WFC': 'Financials',
    'WM': 'Industrials',
    'WMB': 'Energy',
    'WMT': 'Consumer Staples',
    'XEL': 'Utilities',
    'XOM': 'Energy',
    'YUM': 'Consumer Discretionary',
    'ZTS': 'Health Care',
}
